export function createBattleSound({AudioContext}={}){
  let ctx,buffer,muted=true,active=true,disposed=false,lastStep=0;const voices=new Set();
  function unlock(){if(disposed)return;try{const C=AudioContext||globalThis.AudioContext||globalThis.webkitAudioContext;if(!C)return;ctx??=new C();void ctx.resume().catch(()=>{});if(!buffer){buffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*.3),ctx.sampleRate);const d=buffer.getChannelData(0);let seed=77;for(let i=0;i<d.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;d[i]=seed/2147483648-1;}}}catch{}}
  function stop(){for(const v of voices){try{v.source.stop();}catch{}v.source.disconnect();v.filter?.disconnect();v.gain.disconnect();}voices.clear();lastStep=0;}
  function tone(f,end,d=.15,volume=.03,noise=false){if(!ctx||disposed||muted||!active||voices.size>=24)return;const source=noise?ctx.createBufferSource():ctx.createOscillator(),gain=ctx.createGain(),filter=noise?ctx.createBiquadFilter():null,t=ctx.currentTime;
    if(noise){source.buffer=buffer;filter.type='lowpass';filter.frequency.setValueAtTime(f,t);filter.frequency.exponentialRampToValueAtTime(end,t+d);source.connect(filter);filter.connect(gain);}else{source.type='triangle';source.frequency.setValueAtTime(f,t);source.frequency.exponentialRampToValueAtTime(end,t+d);source.connect(gain);}
    gain.gain.setValueAtTime(.001,t);gain.gain.linearRampToValueAtTime(volume,t+.004);gain.gain.exponentialRampToValueAtTime(.001,t+d);gain.connect(ctx.destination);const v={source,gain,filter};voices.add(v);source.onended=()=>{source.disconnect();filter?.disconnect();gain.disconnect();voices.delete(v);};source.start(t);source.stop(t+d+.01);
  }
  function event(e){if(e.type==='shot'){tone(3600,130,.17,e.weapon==='scatter'?.14:.1,true);tone(85,40,.10,.1);}else if(e.type==='enemy-shot')tone(1800,160,.15,.035*(1-(e.distance??0)/50),true);else if(e.type==='hit')tone(1300,750,.04,.035);else if(e.type==='hurt'){tone(160,55,.14,.06,true);}else if(e.type==='reload'){tone(1900,300,.12,.04,true);}else if(['loot','heal'].includes(e.type)){tone(650,980,.2,.04);}else if(e.type==='eliminate'&&e.player){tone(980,520,.25,.04);}else if(e.type==='win'){tone(440,880,.5,.07);}else if(e.type==='lose'){tone(140,45,.45,.06);}}
  return {unlock,event,stop,update(s){if(s.phase==='playing'&&s.player.speed>1&&s.time-lastStep>(s.player.speed>6?.26:.38)){lastStep=s.time;tone(700,90,.065,.022,true);}},setMuted(v){muted=Boolean(v);if(muted)stop();},setActive(v){active=Boolean(v);if(!active)stop();},voices:()=>voices.size,dispose(){disposed=true;stop();void ctx?.close().catch(()=>{});}};
}
