export const CENTURY_CATALOG=Object.freeze([
  {id:'chromatic-lab',title:'色彩炼金',english:'CHROMATIC LAB',category:'sports-precision',inputMode:'hold',artStyle:'glass-laboratory',color:'#268c9a',sound:[810,'sine'],genre:'调色 · 比例判断',levels:['双色配方','三色混合','三分误差'],goals:['把量杯调成样品的颜色','三种原液，控制每种用量','灌满时，比例误差不超过三点'],hint:'按住上方彩色阀门注入原液，松开停止。把下方量杯灌满，颜色尽量接近右侧样品。'},
  {id:'loop-lock',title:'一圈打尽',english:'LOOP & LOOT',category:'experimental-sandbox',inputMode:'drag',artStyle:'jewel-inlay',color:'#b85469',sound:[1240,'sine'],genre:'画圈捕获 · 避开诅咒',levels:['三枚宝石','一圈两枚','三圈五枚'],goals:['用三圈收走三枚宝石','三圈拿四枚，至少合抓一次','三圈拿五枚，别把黑石圈进去'],hint:'按住画一个闭合圈，把宝石圈进去；别圈中黑色尖刺。每关只有三圈，墨线长度有限。'},
  {id:'ink-rail',title:'一笔通车',english:'DRAW THE RAIL',category:'building-balance',inputMode:'drag',artStyle:'woodblock-railway',physics:'matter',color:'#377f91',sound:[190,'triangle'],genre:'画轨道 · 物理行车',levels:['一张车票','山间绕行','三票险路'],goals:['从左站画到右站，沿路拿到车票','让车轮从两张票下面经过','三张票都拿到，别撞悬石'],hint:'从左站按住，一笔向右画轨道，松开后小车出发。轨道画在车票下方一点；收齐车票到右站。'},
  {id:'soda-strata',title:'汽水层层消',english:'SODA STRATA',category:'matching-assembly',inputMode:'tap',artStyle:'soda-pop-print',color:'#d84f79',sound:[560,'triangle'],genre:'成组消除 · 重力连锁',levels:['气泡罐','重排颜色','七步清瓶'],goals:['点掉三个以上相连同色气泡','先消下面，让上面聚成组','在有限步数里清空全部气泡'],hint:'点相连的三个以上同色气泡消除，上方气泡会下落。不补新气泡，清空才过关；剩下孤立气泡会失败。'},
  {id:'leak-patrol',title:'漏水别慌',english:'LEAK PATROL',category:'management-resources',inputMode:'hold',artStyle:'submarine-cel',color:'#3989b0',sound:[175,'sawtooth'],genre:'多点维修 · 积水压力',levels:['六处漏点','八处连漏','十处抢修'],goals:['修好六处漏点，别让水漫过警戒线','同时漏水，先救最危险的地方','修补更慢，积水也更快'],hint:'把鼠标移到漏水阀门上按住修补。可以松开转移目标；破口会持续涨水，水位满就失败。'},
  {id:'quarter-turn',title:'四分之一转',english:'QUARTER TURN',category:'logic-rules',inputMode:'tap',artStyle:'bauhaus-ceramic',color:'#c96846',sound:[510,'triangle'],genre:'局部旋转 · 图案复原',levels:['两次打乱','四次打乱','六次打乱'],goals:['转动四格，把窗花还原','看右侧原图，规划旋转顺序','十次机会，复原九块图案'],hint:'点四个小圆形转轴之一，周围四块顺时针旋转。把大图排成右侧小样的顺序，转轴之间会互相影响。'},
  {id:'stamp-storm',title:'印章风暴',english:'STAMP STORM',category:'stealth-observation',inputMode:'tap',artStyle:'risograph-bureau',color:'#db544c',sound:[280,'square'],genre:'图形辨伪 · 快速盖章',levels:['三枚印记','换样检查','四枚极速'],goals:['与上方样本完全一致才放行','样本会更换，别只记上一张','四个印记都对，才盖绿色章'],hint:'比较单据印记和上方样本。点左边红叉拒收，右边绿勾放行；错三张或漏检三张就失败。'},
  {id:'fridge-fit',title:'冰箱塞塞',english:'FRIDGE FIT',category:'spatial-routing',inputMode:'drag',artStyle:'kitchen-collage',color:'#559573',sound:[380,'triangle'],genre:'异形装箱 · 空间拼合',levels:['四盒满冰箱','五盒没空隙','六盒极限装'],goals:['把四个保鲜盒全部塞进冰箱','五个形状刚好拼满','六盒食材，一个格子也不浪费'],hint:'拖动两侧保鲜盒放入中央格子，不能重叠或越界。形状方向固定，放错可以再拖出来调整。'},
  {id:'knot-office',title:'解结事务所',english:'UNTANGLE OFFICE',category:'spatial-routing',inputMode:'drag',artStyle:'embroidered-wires',color:'#8170a0',sound:[690,'sine'],genre:'拖动端点 · 线路解结',levels:['四点五线','五点七线','六点九线'],goals:['移动端点，让所有线都不相交','七根连线，慢慢理顺','九根连线，一个交叉也不能剩'],hint:'拖动彩色端点，把互相穿过的线分开。红色标记是交叉点；端点不能叠在一起。'},
  {id:'shadow-tell',title:'影子露馅',english:'SHADOW TELLS',category:'stealth-observation',inputMode:'tap',artStyle:'lightbox-pop-art',color:'#3869a9',sound:[960,'sine'],genre:'影子找茬 · 细节辨认',levels:['四件展品','六件障眼法','八件快找'],goals:['找到影子与物品不一致的那件','手柄、齿数、方向，都要看','八件展品中找出唯一破绽'],hint:'每张展品上方是物品，下方是影子。只有一张对不上，点它；三次点错或超时就失败。'},
].map(g=>({...g,kind:'game',release:'preview',collection:'century-ten',canvasPack:true,packFamily:'century-ten',canvasHeight:640,pointInput:true,physics:g.physics||'rules',uiTheme:['loop-lock','knot-office'].includes(g.id)?'dark':'light',hideLevels:true,persistentCheckpoint:true,cover:`/apps/codex-stage/century-ten/assets/covers/${g.id}.png`})));
