export const GAUNTLET_CATALOG=Object.freeze([
  {id:'needle-rush',title:'针尖过山车',english:'THREAD THE NIGHT',mechanic:'moving-aperture-shot',artStyle:'embroidered-midnight',category:'rhythm-timing',inputMode:'tap',color:'#e675aa',sound:[1320,'sine'],genre:'一键穿针 · 提前量',levels:['四个针眼','逆向穿梭','针尖上的六连'],goals:['让线头穿过四个移动针眼','针眼变小，左右反向','六次穿针，错一次就断线'],hint:'点一下把线头送向右侧针眼。针眼一直在移动，要算上飞行时间。'},
  {id:'tightrope-club',title:'楼顶钢丝社',english:'NO SAFETY NET',mechanic:'unstable-balance-control',artStyle:'newspaper-rooftops',category:'building-balance',inputMode:'hold',color:'#d94b41',sound:[270,'triangle'],genre:'单键平衡 · 阵风',levels:['第一条天际线','侧风袭来','最后十八秒'],goals:['保持身体不倾倒，走到对面','风会变向，别修正过头','更窄的平衡区，撑到终点'],hint:'按住向左倾，松开向右倾。把脚下指针留在安全范围里，风来时提前修正。'},
  {id:'mirror-vault',title:'偷一束月光',english:'MOONLIGHT HEIST',mechanic:'optical-routing',artStyle:'optical-black-marble',category:'spatial-routing',inputMode:'tap',color:'#70e4d4',sound:[760,'sine'],genre:'转动镜片 · 激光折射',levels:['两次折射','四镜回路','六镜迷阵'],goals:['把左侧月光送进水晶','镜片只能翻转，观察每次反射','别浪费翻转次数'],hint:'点击斜镜在 / 和反斜线之间切换，把光送进水晶。每关翻转次数有限。'},
  {id:'crate-escape',title:'死角搬运工',english:'NO WAY BACK',mechanic:'irreversible-box-push',artStyle:'warehouse-pixel-isometric',category:'logic-rules',inputMode:'tap',color:'#e3b843',sound:[160,'square'],genre:'推箱子 · 不可逆死角',levels:['别推错方向','双箱错位','三箱仓库'],goals:['把木箱推到黄色标记上','两个箱子，都要留出绕行空间','三箱归位，别把自己封住'],hint:'点角色相邻的地砖走一步。箱子只能推，不能拉；推到死角就得重来。'},
  {id:'twin-tide',title:'双生潜流',english:'TWO AT ONCE',mechanic:'mirrored-dual-navigation',artStyle:'aquarium-duotone',category:'racing-driving',inputMode:'track',color:'#47adcd',sound:[440,'sine'],genre:'一鼠双控 · 镜像避障',levels:['双舱航道','不对称闸门','窄缝双人行'],goals:['左右潜艇一起穿过六道闸','鼠标右移，右艇反而左移','两边同时安全，才算过关'],hint:'左右移动鼠标，两个潜艇镜像移动。提前同时对准两边缺口；撞到任意一边都会失败。'},
  {id:'mine-surveyor',title:'雷区点灯人',english:'LIGHT THE SAFE GROUND',mechanic:'adjacency-deduction',artStyle:'field-notebook',category:'logic-rules',inputMode:'tap',color:'#318d72',sound:[640,'triangle'],genre:'数字推理 · 一错归零',levels:['六乘六地块','七列疑云','八列无人区'],goals:['点亮所有安全地块','数字包含斜角的雷数','没有猜雷，利用已知数字推理'],hint:'数字是周围八格的地雷总数。只点确定安全的暗格，碰一颗雷整关重来。'},
  {id:'territory-cut',title:'别碰我的线',english:'CUT THE CORAL',mechanic:'territory-flood-capture',artStyle:'coral-screenprint',category:'combat-action',inputMode:'drag',color:'#fa8669',sound:[350,'sawtooth'],genre:'划线圈地 · 危险回头路',levels:['占领三成半','夺回半片海','三分之二领地'],goals:['从边界划到边界，占领 35%','游动的光核不能碰到未闭合的线','多切几块，拿到 65%'],hint:'从亮色安全地块按住，横竖划线回到安全区，收走没有光核的一侧。线没闭合前被碰到就失败。'},
  {id:'paper-fold',title:'折到没脾气',english:'FOLD INTO PLACE',mechanic:'fold-and-overlay',artStyle:'origami-cutout',category:'matching-assembly',inputMode:'tap',color:'#cf5685',sound:[520,'triangle'],genre:'叠纸 · 空间预判',levels:['对折两次','折痕会干扰','五折蝴蝶'],goals:['沿虚线对折，让色点叠到右侧样图','折叠会移动一侧所有色点','折叠次数有限，先想再点'],hint:'点中间的虚线圆钮：箭头一侧会沿折痕翻过去，重叠点合并。把色点折成右侧样图。'},
  {id:'tempo-steps',title:'别抢拍',english:'AFTERBEAT',mechanic:'syncopated-hit-windows',artStyle:'concert-poster',category:'rhythm-timing',inputMode:'tap',color:'#edca4f',sound:[830,'square'],genre:'切分节奏 · 精确落拍',levels:['十六拍','切分拍点','六十五毫秒'],goals:['音符到达白线时轻点','有连音和空拍，别凭惯性','允许三次失误，晚一点都不行'],hint:'黄色音符到达中央白线时点一下。不是匀速点，观察长短间隔；声音可关闭。'},
  {id:'airlock-queue',title:'气压急送',english:'PRESSURE EXPRESS',mechanic:'pressure-tracking-arrivals',artStyle:'space-industrial-comic',category:'management-resources',inputMode:'hold',color:'#94bb51',sound:[110,'sawtooth'],genre:'单键气压 · 连续对接',levels:['六次对接','反向调压','十舱连送'],goals:['每个舱到达时，把气压对准绿区','上升有惯性，松手要提前','窄窗口，不给喘气时间'],hint:'按住升压，松开降压。货舱撞线那一刻，指针必须在目标绿区内；漏掉两舱就失败。'},
].map(g=>({...g,kind:'game',release:'preview',collection:'gauntlet-ten',canvasPack:true,packFamily:'gauntlet-ten',canvasHeight:640,pointInput:['mirror-vault','crate-escape','twin-tide','mine-surveyor','territory-cut','paper-fold'].includes(g.id),physics:'rules',uiTheme:['needle-rush','mirror-vault','twin-tide','tempo-steps'].includes(g.id)?'dark':'light',hideLevels:true,persistentCheckpoint:true,cover:`/apps/codex-stage/gauntlet-ten/assets/covers/${g.id}.png`})));
