export const ODD_CATALOG=Object.freeze([
  {id:'velvet-vault',title:'咔哒金库',english:'VELVET VAULT',category:'rhythm-timing',artStyle:'art-deco',color:'#b83f64',inputMode:'hold',sound:[330,'sine'],genre:'转盘 · 听诊开锁',levels:['四道锁舌','反向密码','最后六声'],goals:['依次打开四道锁舌','五道锁舌，停得再准些','六道锁舌，三次失误前打开'],hint:'按住转盘，指针进入绿色刻度时松手。每开一锁，方向反转；三次停错会报警。'},
  {id:'power-wash',title:'高压冲冲洗',english:'WASH REVEAL',category:'experimental-sandbox',artStyle:'street-mural',color:'#218eaa',inputMode:'drag',pointInput:true,sound:[860,'sine'],genre:'冲洗 · 壁画显影',levels:['初见颜色','厚厚一层','最后的壁画'],goals:['洗掉九成污渍','别让水枪过热','时间更紧，冲出完整壁画'],hint:'按住鼠标移动水枪，洗去灰色污渍。温度快满时松开冷却，限时洗净九成墙面。'},
  {id:'zipper-run',title:'拉链别脱轨',english:'ZIP TRIP',category:'sports-precision',artStyle:'denim-stitch',color:'#327bb5',inputMode:'drag',pointInput:true,sound:[430,'triangle'],genre:'拉链 · 沿线穿行',levels:['弯弯一条线','收窄的针脚','曲线加倍'],goals:['把拉链拉到最下方','拉头别碰到两侧红线','一口气穿过急弯'],hint:'抓住金色拉头，沿着弯曲轨道向下拖。拉偏会磨损，松手可暂时停住。'},
  {id:'alarm-alley',title:'闹钟闭嘴',english:'ALARM ALLEY',category:'stealth-observation',artStyle:'pixel-nightstand',color:'#5860af',inputMode:'tap',pointInput:true,sound:[1480,'square'],genre:'反应 · 敲响铃',levels:['八个清晨','闹钟扎堆','最后十二响'],goals:['敲掉八只正在响的闹钟','蓝色睡眠钟不能碰','敲掉十二次响铃'],hint:'点击黄色、正在响铃的闹钟。别敲蓝色睡眠钟；漏掉或敲错三次就起晚了。'},
  {id:'lunar-lease',title:'月面停车费',english:'LUNAR VALET',category:'racing-driving',artStyle:'lunar-instrument',color:'#4ba988',inputMode:'track',pointInput:true,physics:'matter',sound:[105,'sawtooth'],genre:'着陆 · 推力控制',levels:['宽停机坪','节省燃料','窄坪轻落'],goals:['轻轻落在绿色停机坪','移动到右侧平台再着陆','窄平台，垂直速度要慢'],hint:'左右移动鼠标控制飞船方向。按住喷气上升，松开下降；对准绿色平台，轻轻落下。'},
  {id:'jelly-shift',title:'果冻挤挤',english:'JELLY SHIFT',category:'platform-runner',artStyle:'candy-cel',color:'#cf417d',inputMode:'hold',sound:[250,'sine'],genre:'变形 · 挤过闸门',levels:['五道小门','六次变身','七门冲刺'],goals:['扁身钻低门，直身过窄门','看清下一道门的形状','连续通过七道闸门'],hint:'按住变矮变宽，松开变高变窄。低门压扁，窄门松手；撞到门就重来。'},
  {id:'baggage-boogie',title:'行李别乱飞',english:'BAGGAGE BOOGIE',category:'logistics-automation',artStyle:'airport-editorial',color:'#dc604d',inputMode:'drag',pointInput:true,sound:[650,'triangle'],genre:'拖拽 · 颜色分拣',levels:['六件出港','七件赶机','八件急送'],goals:['同色行李拖进同色出口','行李带变快了','别把行李送错航班'],hint:'把传送带上的行李拖进同色出口。放错或漏掉三件失败，没拖到出口则回到传送带。'},
  {id:'fuse-salon',title:'引线理发师',english:'FUSE SALON',category:'combat-action',artStyle:'technical-blueprint',color:'#267c91',inputMode:'drag',pointInput:true,sound:[180,'triangle'],genre:'划切 · 拆弹救场',levels:['四条引线','八条引线','十二条引线'],goals:['划断燃烧引线，别碰金色电缆','分两批剪断引线','三批引线，动作再快一点'],hint:'按住划过黑色引线即可剪断。不要划到横穿中央的金色电缆；火星烧到炸弹就失败。'},
  {id:'tower-unplug',title:'抽薪不倒',english:'GENTLE EXTRACTION',category:'building-balance',artStyle:'woodcut-workshop',color:'#438e7d',inputMode:'drag',pointInput:true,physics:'matter',sound:[220,'triangle'],genre:'抽积木 · 重心平衡',levels:['抽出三层','四层不倒','五层极限'],goals:['抽出三块，楼顶不倒','抽走四块木板','五块木板，屋顶保持平稳'],hint:'抓住一层木板水平抽出，别向上掀。左右交替，留意屋顶重心；抽够数量后等它落稳。'},
  {id:'sugar-snip',title:'剪一口甜',english:'SUGAR SNIP',category:'physics-demolition',artStyle:'cutpaper-confectionery',color:'#c55785',inputMode:'tap',physics:'matter',sound:[1080,'sine'],genre:'剪绳 · 摆荡落点',levels:['第一口甜','移动的糖罐','最后的小罐'],goals:['剪断绳子，把糖送进罐子','糖罐在移动，算好提前量','窄罐子，也要吃到糖'],hint:'糖果摆到合适位置时点一下剪绳。它会沿当前速度飞落，掉进下方的罐子才算成功。'},
].map(g=>({...g,kind:'game',release:'preview',collection:'odd-ten',canvasPack:true,packFamily:'odd-ten',canvasHeight:640,physics:g.physics||'rules',hideLevels:true,persistentCheckpoint:true,cover:`/apps/codex-stage/odd-ten/assets/covers/${g.id}.png`})));
