export const SPORTS_CATALOG=Object.freeze([
  {id:'pocket-six',title:'六袋台球',english:'POCKET SIX',category:'sports-precision',artStyle:'emerald-club',color:'#217963',inputMode:'drag',sound:[960,'sine'],genre:'台球 · 碰撞落袋',hint:'从白球向后拖，松手击球。八杆清掉彩球；白球落袋会罚一杆。',levels:['三球热身','四角走位','五球清台'],goals:['八杆内，三颗彩球进袋','清掉四球，留好白球位置','五球清台，别让白球落袋']},
  {id:'roof-hoops',title:'楼顶投篮',english:'ROOFTOP HOOPS',category:'sports-precision',artStyle:'rooftop-comic',color:'#dc5646',inputMode:'drag',sound:[210,'triangle'],genre:'篮球 · 抛物线',hint:'从篮球向左下拖拽，松手投篮。六次机会命中三球，后两关篮筐会移动。',levels:['天台首投','篮筐在溜达','追风三分'],goals:['六次出手，命中三球','提前量，刚好入筐','接住移动篮筐的节奏']},
  {id:'curve-kick',title:'弧线任意球',english:'BEND IT',category:'sports-precision',artStyle:'football-broadcast',color:'#369752',inputMode:'drag',sound:[160,'triangle'],genre:'足球 · 绕墙破门',hint:'从球向后拉，松手踢出弧线。左右拉偏能绕过人墙，躲开守门员，七脚进三球。',levels:['越过人墙','第三名后卫','门将快一步'],goals:['七脚机会，三次破门','绕过三人墙再入网','瞄准门将来不及扑的角落']},
  {id:'lawn-rally',title:'草地网球',english:'LAWN RALLY',category:'sports-precision',artStyle:'gouache-tennis',color:'#7c913c',inputMode:'track',sound:[540,'triangle'],genre:'网球 · 移动接球',hint:'左右移动鼠标或拖动球拍接球。击中球拍边缘可打斜线，先得三分胜出。方向键也可移动。',levels:['草地初赛','对手提速','决胜盘'],goals:['先拿三分','打向对手的空档','小球拍，大角度']},
  {id:'table-spin',title:'乒乓接杀',english:'QUICK SPIN',category:'rhythm-timing',artStyle:'cel-sports-gym',color:'#d74047',inputMode:'tap',sound:[1340,'sine'],genre:'乒乓球 · 时机挥拍',hint:'球到左侧球拍附近时，点一下挥拍。把球打过网并落到对面台面，失误三次重来。',levels:['第一板','连续五板','六板接杀'],goals:['接回四球','速度加快，接回五球','更高的网，连续六板']},
  {id:'pin-strike',title:'保龄球连锁',english:'PIN CASCADE',category:'physics-demolition',artStyle:'polished-bowling',color:'#ab3752',inputMode:'drag',sound:[110,'triangle'],genre:'保龄球 · 一击连锁',hint:'从球向后拉，松手出手。每关两球，利用球瓶碰撞连锁击倒目标。',levels:['八瓶入门','偏心九瓶','十瓶全倒'],goals:['两球击倒八瓶','略微偏开的九瓶目标','两球清掉全部十瓶']},
  {id:'ice-stone',title:'冰壶擦线',english:'ICE & EDGE',category:'sports-precision',artStyle:'winter-postcard',color:'#2999a4',inputMode:'hold',sound:[680,'sine'],genre:'冰壶 · 力道与刹点',hint:'按住蓄力，松手推壶。滑行中按住扫冰可再滑远一点。三壶累计靶分，靶心三分。',levels:['冰上四分','绕开护壶','最后六分'],goals:['三壶拿到四分','有护壶挡路，拿到五分','把握摩擦，累计六分']},
  {id:'domino-bridge',title:'多米诺过桥',english:'CHAIN REACTION',category:'logic-rules',artStyle:'stopmotion-workbench',color:'#d29c27',inputMode:'hold',sound:[790,'triangle'],genre:'多米诺 · 放桥连锁',hint:'按住让桥左右移动。松手停桥并推第一块牌，让连锁越过缺口、倒到最后。',levels:['桥要对齐','窄一点的桥','最后一条缝'],goals:['把二十块牌连到终点','桥变窄了，停得再准些','最窄的桥，一路倒到底']},
  {id:'plate-parade',title:'叠盘杂技',english:'PLATE PARADE',category:'building-balance',artStyle:'paper-collage-kitchen',color:'#cb3663',inputMode:'track',sound:[1560,'sine'],genre:'叠盘 · 移动平衡',hint:'左右移动托盘，接住掉下来的盘子。让落点靠近盘堆中心，全部接稳才过关。方向键也可移动。',levels:['五盘上菜','六盘不晃','七盘杂技'],goals:['五只盘子，稳稳叠好','六只盘子，托盘更窄','七盘高塔，不掉一只']},
  {id:'crush-hour',title:'回收压压乐',english:'CRUSH HOUR',category:'rhythm-timing',artStyle:'industrial-screenprint',color:'#e2b329',inputMode:'hold',sound:[95,'sawtooth'],genre:'液压机 · 压碎与放行',hint:'按住压下，松手抬起。压碎箱子和金属，让红色电池完整通过；误压电池立即停机，漏件三次重来。',levels:['回收六件','流水线提速','八件不漏'],goals:['压碎六件，电池放行','更快的七件回收','八件挑战，保持节奏']},
].map(g=>({...g,kind:'game',release:'preview',collection:'sports-ten',canvasPack:true,packFamily:'sports-ten',canvasHeight:640,physics:'matter',hideLevels:true,persistentCheckpoint:true,cover:`/apps/codex-stage/sports-ten/assets/covers/${g.id}.png`})));
