export const HARDCORE_CATALOG=Object.freeze([
  {id:'ratchet-vault',title:'棘轮登塔',english:'RATCHET / RELEASE',mechanic:'tangent-momentum-transfer',artStyle:'industrial-linocut',category:'platform-runner',physics:'matter',inputMode:'tap',color:'#f0693d',sound:[180,'sawtooth'],genre:'单击脱钩 · 切线飞行',levels:['六次借力','八级悬空','十级无退路'],goals:['单击脱离转轮，飞进下一只亮色抓环','飞出去就不能修正，六次变成八次','十次连续接力，碰不到抓环就归零'],hint:'转轮会带着你旋转。单击沿切线飞出去，接住右侧亮色抓环。出手后不能修正，失手整关重来。'},
  {id:'hex-panic',title:'六角封锁',english:'HEX / LOCKDOWN',mechanic:'contracting-ring-navigation',artStyle:'signal-red-geometric',category:'combat-action',inputMode:'hold',color:'#fa574a',sound:[220,'square'],genre:'按住反转 · 缺口求生',levels:['十四层封锁','十八层急转','二十二层极限'],goals:['按住逆时针，松手顺时针，钻过每一道缺口','提前看外圈，连续十八次避开红墙','二十二道封锁，一次碰撞立即结束'],hint:'按住逆时针转，松开顺时针转。缺口会一层层靠近，提前移进去；碰红墙就失败。'},
  {id:'downshaft',title:'倒悬矿井',english:'SHAFT / ZERO',mechanic:'limited-thrust-descent',artStyle:'two-tone-pixel-shaft',category:'platform-runner',physics:'matter',inputMode:'track',color:'#f1c84e',sound:[120,'triangle'],genre:'鼠标横移 · 点火刹降',levels:['六道断层','八道窄缝','深井十连'],goals:['左右移鼠标，点一下点火减速，从缺口下潜','每道闸只有三次刹降，穿过才补充','缺口更窄，点火也要算提前量'],hint:'左右移动鼠标调整落点，单击喷气刹降。每过一道闸补满三格燃料，撞到石板整关重来。'},
  {id:'magnet-suture',title:'磁针手术',english:'MAGNET / MICROSURGERY',mechanic:'indirect-spring-guidance',artStyle:'medical-enamel-cutaway',category:'sports-precision',physics:'matter',inputMode:'track',color:'#239e8e',sound:[660,'sine'],genre:'隔空牵引 · 惯性过弯',levels:['弯管缝合','窄腔操作','毫米级手术'],goals:['鼠标是磁铁，不是钢珠；慢慢牵过全部弯道','钢珠有惯性，转角要先刹住','触壁即失败，先控制速度再赶时间'],hint:'移动鼠标磁铁，隔空牵引钢珠经过所有检查环。钢珠不会立即跟手，碰管壁就失败。'},
  {id:'flash-dojo',title:'刹那居合',english:'ONE / CLEAN CUT',mechanic:'telegraphed-feint-parry',artStyle:'ink-red-theatre',category:'combat-action',inputMode:'tap',color:'#c93644',sound:[900,'triangle'],genre:'见红再斩 · 抢拍必败',levels:['八次出刀','十次试探','十二次无伤'],goals:['蓝色是佯攻，红色刀印亮起才单击','看收拢的刀环，别被佯攻骗走','十二次连续命中，早按晚按都失败'],hint:'只在红色“斩”出现时单击。蓝色“静”是佯攻。环圈提示出刀时机，按早或按晚都要重来。'},
  {id:'rotor-courier',title:'转杆快递',english:'HANDLE / WITH ROTATION',mechanic:'rotating-rigid-body-navigation',artStyle:'blueprint-cyan-print',category:'spatial-routing',physics:'matter',inputMode:'track',color:'#e5c84c',sound:[340,'triangle'],genre:'长杆自转 · 卡角运输',levels:['带杆过弯','窄巷转向','最后一厘米'],goals:['移动鼠标运送自转长杆，杆的两头都不能碰墙','在转角等合适角度，再穿过窄道','不能瞬移，任何一端碰墙整关重来'],hint:'移动鼠标带着长杆走，长杆会自己旋转。两端都要避墙，过弯时停下来等角度，穿过检查点抵达右端。'},
  {id:'knight-fall',title:'烧桥骑士',english:'KNIGHT / NO RETURN',mechanic:'self-consuming-knight-tour',artStyle:'woodcut-chess-islands',category:'logic-rules',inputMode:'tap',color:'#547fad',sound:[360,'triangle'],genre:'日字跳跃 · 踩过即塌',levels:['十二座孤岛','十八步残局','二十四桥尽毁'],goals:['走日字，踩遍亮格，最后落到旗帜','离开的格子会塌，不能走回头路','把全部孤岛走完，再去终点'],hint:'按国际象棋马的日字走法跳跃，亮边是可去的位置。每格只能踩一次，踩完全部格子后到旗帜；走进死路就重来。'},
  {id:'polarity-lock',title:'反转熔炉',english:'POLARITY / BLACKOUT',mechanic:'bounded-toggle-linear-puzzle',artStyle:'stained-glass-machine',category:'logic-rules',inputMode:'tap',color:'#c876b0',sound:[510,'sine'],genre:'联动翻转 · 有限步熄灯',levels:['十字联动','对角回路','混合极性'],goals:['点一个开关，会同时翻转它与相邻灯','本关变成斜角联动，不是上一关的十字','不同位置不同线路，熄灭全部亮灯'],hint:'点击会翻转本格和连线相邻的灯。把所有亮灯熄灭；步数有限，没有撤销。图中的细线就是连接关系。'},
  {id:'disc-vault',title:'刀盘密室',english:'DISC / ESCAPE',mechanic:'moving-hazard-objective-dodge',artStyle:'hazard-magenta-comic',category:'shooter-bullethell',physics:'matter',inputMode:'track',color:'#e271a2',sound:[240,'sawtooth'],genre:'鼠标闪避 · 密室取钥',levels:['三盘取钥','五盘封门','七盘绝境'],goals:['移动鼠标躲开刀盘，依次取完六把钥匙','刀盘更多，取钥必须穿过房间','七只刀盘，不能站在角落等通关'],hint:'移动鼠标带着角色躲刀盘，依次触碰黄色钥匙。刀盘会真实碰墙反弹；一次碰撞失败。'},
  {id:'echo-rewind',title:'回声倒带',english:'ECHO / REVERSE',mechanic:'reverse-spatial-sequence-recall',artStyle:'retro-tape-console',category:'stealth-observation',inputMode:'tap',color:'#e79536',sound:[570,'sine'],genre:'反向记忆 · 一错清空',levels:['倒放六拍','倒放八拍','倒放十拍'],goals:['看完六个亮格，再按相反顺序点回去','不是重复原顺序，要从最后一个开始','十拍倒放，点错一格就重来'],hint:'先看九宫格闪烁的顺序。出现倒放符号后，从最后一个开始反着点。展示期间点按无效，回答时一错归零。'},
].map(g=>({...g,kind:'game',release:'preview',collection:'hardcore-ten',canvasPack:true,packFamily:'hardcore-ten',canvasHeight:640,physics:g.physics||'rules',pointInput:['downshaft','magnet-suture','rotor-courier','knight-fall','polarity-lock','disc-vault','echo-rewind'].includes(g.id),uiTheme:['hex-panic','downshaft','polarity-lock','disc-vault','echo-rewind'].includes(g.id)?'dark':'light',hideLevels:true,persistentCheckpoint:true,cover:`/apps/codex-stage/hardcore-ten/assets/covers/${g.id}.png`})));
