export const CHALLENGE_CATALOG=Object.freeze([
  {id:'crosswalk-zero',title:'零点过街',english:'MIDNIGHT CROSSING',category:'rhythm-timing',artStyle:'paper-city',color:'#3b7f8e',inputMode:'tap',physics:'matter',sound:[610,'triangle'],genre:'一步一险 · 车流预判',levels:['三条车道','货车来了','五线穿城'],goals:['穿过车流，到对面广场','大货车更长，留好间隔','看好两辆车之间的空档'],hint:'每点一下向前跳一格。草地上等车过去，别在马路中央发呆；撞车就重来。'},
  {id:'faultline-drill',title:'断层钻头',english:'FAULTLINE',category:'racing-driving',artStyle:'mining-linocut',color:'#c54c38',inputMode:'tap',sound:[120,'sawtooth'],genre:'折返钻地 · 缝隙穿行',levels:['六层矿脉','窄缝深挖','断层急转'],goals:['穿过六处岩层缺口','缺口更窄，早点转向','更深更快，别撞岩壁'],hint:'钻头自动斜向下钻。点一下左右反向，穿过岩层中间的亮色缺口。'},
  {id:'laser-limbo',title:'激光借过',english:'RED / WHITE',category:'stealth-observation',artStyle:'swiss-brutalist',color:'#d94446',inputMode:'track',pointInput:true,physics:'matter',sound:[970,'sine'],genre:'自由移动 · 动态缝隙',levels:['三道红线','窄门移动','精密穿越'],goals:['穿过三道激光，抵达出口','提前对准移动缺口','窄缝中别贪快'],hint:'移动鼠标引导青色光点，穿过每条红线的移动缺口。碰到激光就失败。'},
  {id:'blackout-bridge',title:'熄灯之后',english:'AFTER THE LIGHT',category:'logic-rules',artStyle:'charcoal-engraving',color:'#497f86',inputMode:'tap',pointInput:true,sound:[380,'sine'],genre:'短时记忆 · 暗桥过河',levels:['四步回忆','五步夜路','六步无灯'],goals:['记住亮起的四块石头','熄灯后走对五步','记住六步，别走进水里'],hint:'先记住从下往上亮起的路径。熄灯后，每行点一块石头；走错一步就落水。'},
  {id:'glass-divide',title:'一刀两半',english:'EXACTLY HALF',category:'sports-precision',artStyle:'stained-glass',color:'#358b94',inputMode:'drag',pointInput:true,physics:'matter',sound:[1600,'sine'],genre:'空间判断 · 面积分割',levels:['七分误差','四分误差','两分误差'],goals:['把玻璃分成接近一半','两边面积相差更小','每边接近 50%，误差两点内'],hint:'从玻璃外按住，划穿玻璃并松手。两块面积越接近越好；每关三刀机会。'},
  {id:'neon-coil',title:'只准右转',english:'RIGHT TURN ONLY',category:'spatial-routing',artStyle:'crt-wireframe',color:'#36957d',inputMode:'tap',sound:[260,'square'],genre:'单键转弯 · 尾迹避障',levels:['四枚电池','向内盘绕','六枚极限'],goals:['吃到四枚电池，别撞自己','五枚电池，路线往内收','更快的六枚电池路线'],hint:'自动前进，每点一下在下一格右转。吃电池，但别撞边框或自己留下的线路。'},
  {id:'freeze-frame',title:'暂停键逃生',english:'FREEZE FRAME',category:'platform-runner',artStyle:'clay-stopmotion',color:'#ba4d48',inputMode:'hold',sound:[165,'triangle'],genre:'冻结机关 · 冷量管理',levels:['四台切割机','冷量紧张','高速生产线'],goals:['让四把锯停在头顶','冷量更少，分段使用','跑得更快，提前冻结'],hint:'角色自动向前跑。按住冻结所有锯片，自己继续跑；松开恢复并补冷量。别把低处的锯冻住。'},
  {id:'copper-balance',title:'偏心装货',english:'COPPER BALANCE',category:'building-balance',artStyle:'scientific-etching',color:'#3a867d',inputMode:'tap',pointInput:true,physics:'matter',sound:[520,'triangle'],genre:'物理天平 · 重量取舍',levels:['八件货','十件偏心','十二件险局'],goals:['装下八件，别让天平翻倒','十件货，重的别放同一边','十二件装稳再过关'],hint:'看下一件的重量，点击天平左边或右边投放。左右平衡，别让货物滑掉；空格使用当前指向的一侧。'},
  {id:'traffic-tangle',title:'路口别打结',english:'CROSSING CONTROL',category:'management-resources',artStyle:'toy-traffic',color:'#457bba',inputMode:'tap',physics:'matter',sound:[720,'triangle'],genre:'红绿灯 · 排队调度',levels:['十二辆通行','十六辆高峰','二十辆晚高峰'],goals:['让两方向共十二辆通过','别让任何一侧排到六辆','忙碌路口，留意交叉车流'],hint:'点一下切换横向和纵向绿灯，黄灯时双方等待。避免车队排满或在路口碰撞。'},
  {id:'shield-waltz',title:'星环守卫',english:'SHIELD WALTZ',category:'shooter-bullethell',artStyle:'prismatic-space',color:'#a24f88',inputMode:'track',pointInput:true,sound:[310,'triangle'],genre:'旋转护盾 · 连续格挡',levels:['八次防御','十次夹击','十二次风暴'],goals:['挡下八束冲击','护盾变窄，挡下十束','十二束快速袭击'],hint:'把鼠标移到核心周围，转动护盾迎向来袭光束。按来袭先后依次拦截，漏掉三次失败。'},
].map(g=>({...g,kind:'game',release:'preview',collection:'challenge-ten',canvasPack:true,packFamily:'challenge-ten',canvasHeight:640,physics:g.physics||'rules',uiTheme:['faultline-drill','blackout-bridge','glass-divide','neon-coil','shield-waltz'].includes(g.id)?'dark':'light',hideLevels:true,persistentCheckpoint:true,cover:`/apps/codex-stage/challenge-ten/assets/covers/${g.id}.png`})));
