import test from 'node:test';
import assert from 'node:assert/strict';
import {createStatueWorld} from './world.js';
const tick=(w,t)=>{for(let i=0;i<t*120;i++)w.step(1000/120);};
function play(w){w.begin();for(let n=0;n<120*90;n++){const s=w.snapshot();if(s.phase!=='playing')return s;w.hold(s.guards.every(g=>g.mode==='away'));w.step(1000/120);}return w.snapshot();}
test('waits for input and a continuous blind run gets caught',()=>{const w=createStatueWorld();tick(w,5);assert.equal(w.snapshot().time,0);w.begin();w.hold(true);tick(w,15);assert.equal(w.snapshot().phase,'lost');});
test('all three objects reach the actual exit through legal timed input',()=>{const w=createStatueWorld();for(let stage=0;stage<3;stage++){const s=play(w);assert.equal(s.phase,stage===2?'won':'caught',JSON.stringify(s));assert.ok(s.x>=820);assert.equal(s.stage,stage);if(stage<2)w.next();}});
test('heavy cargo keeps moving after release but eventually settles',()=>{const w=createStatueWorld({checkpoint:{version:1,stage:2}});w.begin();w.hold(true);tick(w,1);w.hold(false);const x=w.snapshot().x;tick(w,.2);assert.ok(w.snapshot().x>x+4);tick(w,2);assert.ok(w.snapshot().speed<2);});
test('suspicion can be recovered by stopping during the inspection window',()=>{const w=createStatueWorld();w.begin();w.hold(true);for(let n=0;n<120*7;n++){w.step(1000/120);if(w.snapshot().suspicion>.2)break;}assert.ok(w.snapshot().suspicion>.2);w.hold(false);tick(w,1);assert.equal(w.snapshot().phase,'playing');assert.ok(w.snapshot().suspicion<.2);});
test('waiting does not earn a checkpoint and taps cannot teleport the player',()=>{const w=createStatueWorld();w.begin();tick(w,30);assert.equal(w.snapshot().phase,'playing');assert.equal(w.snapshot().x,100);for(let n=0;n<100;n++){w.hold(true);w.hold(false);}assert.equal(w.snapshot().x,100);});
test('cancel and stop reject further motion; restart restores a safe unheld stage',()=>{const w=createStatueWorld();w.begin();w.hold(true);tick(w,1);w.cancel();assert.equal(w.snapshot().held,false);w.stop();const s=JSON.stringify(w.snapshot());tick(w,8);w.hold(true);assert.equal(JSON.stringify(w.snapshot()),s);const r=createStatueWorld({checkpoint:w.checkpoint()});assert.equal(r.snapshot().phase,'ready');assert.equal(r.snapshot().held,false);});
test('checkpoint is bounded, stage completion is explicit, corrupt saves cannot skip stages',()=>{for(const cp of [null,{version:1,stage:9},{version:1,stage:-1},{version:2,stage:2}])assert.equal(createStatueWorld({checkpoint:cp}).snapshot().stage,0);const w=createStatueWorld();assert.equal(w.next(),false);w.begin();w.hold(true);tick(w,10);w.retry();assert.equal(w.snapshot().phase,'ready');assert.ok(JSON.stringify(w.checkpoint()).length<100);});
test('invalid times and stopped inputs cannot change the game; destroy is final',()=>{const w=createStatueWorld();w.begin();w.step(NaN);w.step(-10);assert.equal(w.snapshot().time,0);w.destroy();assert.equal(w.begin(),false);assert.equal(w.hold(true),false);});
